"""Add admin users table

Revision ID: a4b348d907dd
Revises: e3c9d20011ca
Create Date: 2025-09-25 10:42:21.677801+00:00

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a4b348d907dd'
down_revision = 'e3c9d20011ca'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###